ParameterSelection:
  # define detector
  NewMatchPathValueDetector:
    # define how the variables (or paths) are selected/filtered
    Variables:
      # pre-filter static variables
      PreFilter:
        Static: {} # {} means no additional parameters are necessary or use default
      # select stable variables from the set of filtered variables
      Select:
        Stable:
          # define configuration parameters
          how: by_occurrence
          segment_threshs: [1.0, 0.165, 0.027, 0.005, 0.001]

  NewMatchPathValueComboDetector:
    Variables:
      PreFilter:
        Static: {}
        Random: {}
        MinMaxOccurrence:
          how: less_than
          thresh: 0.005
      Select:
        CoOccurrenceCombos:
          min_co_occurrence: 0.1

  CharsetDetector:
    Variables:
      PreFilter:
        Static: {}
      Select:
        Stable:
          how: by_charset
          segment_threshs: [1.0, 0.36788, 0.13534, 0.04979, 0.01832, 0.00674, 0.00248, 0.00091, 0.00034, 0.00012]

  EntropyDetector:
    Variables:
      PreFilter:
        Static: {}
      Select:
        CharacterPairProbability:
          mean_crit_thresh: 0.7
    SpecificParams:
      CharacterPairProbabilityThresh:
        parameter_name: prob_thresh
        min: 0.0
        max: 0.9
        offset: -0.05

  ValueRangeDetector:
    Variables:
      Select:
        Stable:
          how: by_valueRange
          segment_threshs: [1.0, 0.36788, 0.13534, 0.04979, 0.01832, 0.00674, 0.00248, 0.00091, 0.00034, 0.00012]

  EventFrequencyDetector:
    Variables:
      PreFilter:
        MinMaxOccurrence:
          how: less_than
          thresh: 5
          rel: false
      Select:
        EventFrequencyAnalysis:
          season_min_autocorrelation: 0
          season_min_reps: 3
          season_variation_coeff: 0.1
          season_planB: null #e.g. 24h - 86400s
          events_per_window: 0.25 # 0.5 for Apache, 0.25 for audit
          unique_events_per_window: true
          operation: mean
    SpecificParams:
      EventFrequencyParams: {}

  EventSequenceDetector:
    Variables:
      PreFilter:
        Static: {}
      Select:
        Stable:
          how: by_eventSequence
          segment_threshs: [1.0, 0.165, 0.027, 0.005, 0.001]
    SpecificParams:
      EventSequenceLength:
        parameter_name: seq_len


Optimization:
  SampleSplit:
    k: 3
    detectors: all # or specify detectors e.g. detectors: [NewMatchPathValueDetector, NewMatchPathValueComboDetector]
    max_FP: 10
    max_FP_per_minute: 0.05
    weighted_split: true
    fancy: true
    thresh_optimization:
      EntropyDetector:
        parameter_name: prob_thresh
        min: 0.0
        max: 0.9
        offset: -0.1

